package org.jodaengine.eventmanagement.adapter.timer;

import org.jodaengine.eventmanagement.adapter.AbstractAdapterEvent;
import org.jodaengine.eventmanagement.adapter.configuration.AdapterConfiguration;

/**
 * Represents a TimerEvent.
 */
public class TimerAdapterEvent extends AbstractAdapterEvent {

    /**
     * Instantiates a new {@link TimerAdapterEvent timerEvent} that is generated by the {@link TimerAdapter}.
     * 
     * @param configuration
     *            - the configuration of the {@link TimerAdapterConfiguration}
     */
    public TimerAdapterEvent(AdapterConfiguration configuration) {

        super(configuration);
    }
}
