package de.hpi.oryxengine.plugin.scheduler;

import de.hpi.oryxengine.plugin.Plugin;


/**
 * The below Javadoc comment is awesome and it was autogenerated.
 * I know I should delete it, but I can't. I dunno if it is correct :P
 * I know however, that if this interface should be implemented by a Plugin.
 * 
 * The listener interface for receiving scheduler events.
 * The class that is interested in processing a scheduler
 * event implements this interface, and the object created
 * with that class is registered with a component using the
 * component's <code>addSchedulerListener</code> method. When
 * the scheduler event occurs, that object's appropriate
 * method is invoked.
 *
 * @see SchedulerEvent
 */
public interface SchedulerListener extends Plugin {
    
    /**
     * This method gets called whenever a process instance is submitted to the scheduler.
     */
    void processInstanceSubmitted();
    
    /**
     * This method gets called whenever a process instance is retreived from the scheduler.
     */
    void processInstanceRetrieved();
}
